server:
  port: 8081

#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            #'my-backend-service' 에 대한 인스턴스 정의
#            alim-service:
              # 서로 다른 인스턴스를 로드벨런서가 사용한다 가정
              # 클라이언트인 user 서비스에서 alim 서비스를 호출
              # 도커로 따지면 컨테이너 네임
#              - service-id: alim-service
#                uri: http://localhost:8082
#              - service-id: alim-service
#                uri: http://localhost:8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # eureka에 client로 등록
    fetch-registry: true # Service registry list 를 가져오겠다
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 컨테이너 디렉토리 마운트와 별개로 테이블을 삭제하고 다시만듦
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false # context 를 보장?
    # 사실 아래의 속성은 이제 강제를 하는 중이므로 필요 없는 속성
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  expires-in: 86400 # 1day
  mobile-expires-in: 31536000
  table-expires-in: 31536000
  secret-key: AADfas21323123ohofgdakllew32dsfasdTG764Gdslkj298GsWg86G # 대칭키로 사용