server:
  port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            #'my-backend-service' 에 대한 인스턴스 정의
            alim-service:
              # 서로 다른 인스턴스를 로드벨런서가 사용한다 가정
              # 클라이언트인 user 서비스에서 alim 서비스를 호출
              - service-id: alim-service
                uri: http://localhost:8082
              - service-id: alim-service
                uri: http://localhost:8082